/**
 * dsh-win-terminal-inspector — DSH host-composition plugin for Windows.
 *
 * Provides the missing win32 terminal inspection for persistent/PTY shells:
 * @deepseek-ai/dsh-subprocess-local's createProcessInspector() only supports
 * linux/darwin and throws "subprocess-local: terminal inspection is
 * unsupported on platform win32" when a terminal (persistent bash) spawns.
 *
 * Injection point (no node_modules patching):
 * LocalSubprocessRuntime.spawnTerminal reads the public `terminalInspector`
 * test hook: `this.terminalInspector ?? createProcessInspector()`. This
 * plugin wraps `spawnTerminal` on the live runtime instance so every Windows
 * terminal gets its own WindowsProcessInspector, which is then attached to
 * the spawned node-pty terminal for authentic ConPTY Ctrl-C delivery.
 *
 * Local extension (this machine): on win32, if the terminal argv starts with
 * a non-existent bash path (the upstream default is "/bin/bash"), rewrite
 * argv[0] to the first existing Git Bash on the candidates list. Agent-preset
 * files are regenerated by preset plugins on host restart, so preset edits
 * are NOT durable; this plugin directory is not touched by them, making it
 * the durable injection point.
 *
 * Both mutations are instance-level, guarded, and fully reversible on
 * dispose, so loader hot-reloads and rollbacks leave the runtime untouched.
 */
import { existsSync } from "node:fs";
import { WindowsProcessInspector } from "./lib/inspector.js";

export const name = "dsh-win-terminal-inspector";
export const inject = ["subprocess"];

const WINDOWS_BASH_CANDIDATES = [
  process.env.DSH_BASH_PATH,
  "C:\\Program Files\\Git\\bin\\bash.exe",
  "C:\\Program Files (x86)\\Git\\bin\\bash.exe",
  "C:\\Windows\\System32\\bash.exe",
].filter(Boolean);

function firstExistingBash() {
  for (const candidate of WINDOWS_BASH_CANDIDATES) {
    if (existsSync(candidate)) return candidate;
  }
  return undefined;
}

/** True when argv[0] names a bash whose path does not resolve to a file. */
function needsBashRewrite(argv0) {
  if (typeof argv0 !== "string" || argv0.length === 0) return false;
  if (existsSync(argv0)) return false;
  return /(^|[\\/])bash(\.exe)?$/i.test(argv0);
}

export function apply(ctx) {
  if (process.platform !== "win32") return;
  const runtime = ctx.subprocess;
  if (runtime === undefined || typeof runtime.spawnTerminal !== "function") return;
  const original = runtime.spawnTerminal;

  // Serialize spawns: `terminalInspector` is a single instance field read by
  // spawnTerminal, so overlapping spawns must not interleave their
  // set/clear. Terminal spawns are rare; the queue adds no real latency.
  let chain = Promise.resolve();
  const wrapped = (spec) => {
    const run = chain.then(async () => {
      const inspector = new WindowsProcessInspector();
      runtime.terminalInspector = inspector;
      try {
        // Windows shell-path rewrite: the upstream default shellPath is
        // "/bin/bash", which does not exist on this machine. Preset files get
        // regenerated by their plugins on restart, so rewrite here instead.
        const argv = Array.isArray(spec?.argv) ? spec.argv : [];
        if (argv.length > 0 && needsBashRewrite(argv[0])) {
          const bash = firstExistingBash();
          if (bash !== undefined) {
            spec = { ...spec, argv: [bash, ...argv.slice(1)] };
          }
        }
        const handle = await original.call(runtime, spec);
        if (handle !== undefined && handle.terminal !== undefined) inspector.attach(handle.terminal);
        return handle;
      } finally {
        if (runtime.terminalInspector === inspector) runtime.terminalInspector = undefined;
      }
    });
    chain = run.then(() => {}, () => {});
    return run;
  };

  runtime.spawnTerminal = wrapped;
  return () => {
    if (runtime.spawnTerminal === wrapped) delete runtime.spawnTerminal;
  };
}

export { WindowsProcessInspector } from "./lib/inspector.js";
