import assert from 'node:assert/strict'
import { parseCodexTurn, runStopGate } from './stop-gate.mjs'

const row = (payload) => ({ type: 'response_item', payload })
const context = (turn_id) => ({ type: 'turn_context', payload: { turn_id } })
const edit = (file) => row({ type: 'custom_tool_call', name: 'apply_patch', call_id: file, input: '*** Begin Patch\n*** Update File: ' + file + '\n*** End Patch' })
const jsonl = (entries) => entries.map((entry) => JSON.stringify(entry)).join('\n')
const parse = (entries, id = 'now') => parseCodexTurn(jsonl(entries), id)
const invoke = (entries, extra = {}, env = {}) => runStopGate(JSON.stringify({ turn_id: 'now', transcript_path: 'fixture', ...extra }), env, { readTranscript: () => jsonl(entries) })
const entries = [context('old'), edit('old.js'), context('now'), edit('new.js')]
assert.deepEqual(parse(entries).edits.map((entry) => entry.file), ['new.js'])
assert.equal(invoke(entries).decision, 'block')
assert.ok(invoke(entries, { stop_hook_active: true }).systemMessage)
assert.ok(invoke(entries, {}, { DSH_STOP_GATE: 'warn' }).systemMessage)
assert.equal(invoke(entries, {}, { DSH_STOP_GATE: 'off' }), null)
assert.equal(invoke(entries, {}, { DSH_STOP_GATE_IGNORE: '\\.js$' }), null)
assert.deepEqual(parse(entries, 'absent').edits, [])
const nested = row({ type: 'custom_tool_call', name: 'exec', call_id: 'nested', input: 'const patch = "*** Begin Patch\\n*** Add File: nested.js\\n*** End Patch"; await tools.apply_patch(patch); text(await tools.mcp__dsh__verify_report({}));' })
const output = row({ type: 'custom_tool_call_output', call_id: 'nested', output: [{ type: 'text', text: JSON.stringify({ content: [{ type: 'text', text: JSON.stringify({ verdict: 'pass' }) }] }) }] })
assert.deepEqual(parse([context('now'), nested]).edits.map((entry) => entry.file), ['nested.js'])
assert.equal(invoke([context('now'), nested, output]), null)
assert.equal(parse([context('now'), nested, output]).verifies[0].verdict, 'pass')
const failed = row({ type: 'function_call_output', call_id: 'verify', output: JSON.stringify({ verdict: 'fail', counts: { fail: 1 } }) })
assert.match(invoke([...entries, row({ type: 'function_call', name: 'mcp__dsh__verify_report', call_id: 'verify', arguments: '{}' }), failed]).systemMessage, /fail 1/)
const prompt = row({ type: 'message', role: 'user', content: [{ type: 'input_text', text: 'fixture prompt' }] })
assert.deepEqual(parse([prompt, edit('old.js'), prompt, edit('last.js')]).edits.map((entry) => entry.file), ['last.js'])
assert.equal(invoke([{ other: true }]), null)
assert.equal(parse([context('now'), row({ type: 'custom_tool_call', name: 'exec', input: 'text("tools.verify_report({})");' })]).verifies.length, 0)
assert.equal(parse([context('now'), row({ type: 'function_call', name: 'exec_command', arguments: JSON.stringify({ cmd: 'echo fixture > a.js' }) })]).edits.length, 0)
console.log('PASS Codex Stop: current turn, fallback prompt, nested patch/verdict, modes and unknown format')
