// dsh-build 单测：BV-03 —— 早返回路径不得让渲染层抛异常
//
// 真机/审计确证的链路：
//   build() 有 6 条早返回只写 `{ ok:false, error }`（**没有 errors 字段**）
//   → renderBuild 无条件读 `v.errors.length`
//   → TypeError
//   → 宿主把它换成 `INVALID_TOOL_OUTPUT: output.render failed`
//   → **唯一能自救的那句话被整个吃掉**（最常见的触发就是"没传 repoRoot"）。
//
// 这里两道一起钉：
//   ① 端到端：真调 build({repoRoot: 不存在的路径})，确认返回形状完整、渲染不抛、且给得出下一步；
//   ② 渲染层：任何形状（含未来新增的）都不许抛 —— 少说可以，吃掉错误不行。
import { mkdtempSync, rmSync, existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { makeBuilder } from '../lib/builder.mjs'
import { renderBuild } from '../lib/render.mjs'

let failures = 0
function check(name, cond, extra = '') {
  if (cond) console.log('  ok   ' + name)
  else { failures++; console.log('  FAIL ' + name + (extra ? ' — ' + extra : '')) }
}

const TMP = mkdtempSync(join(tmpdir(), 'dsh-build-bv03-'))

// ------------------------------------------------- 1. 端到端：真调 build()，repoRoot 不存在
{
  const logsDir = join(TMP, 'logs')
  const b = makeBuilder({ logsDir, repoRoot: '', clientRoot: '' })
  const missing = join(TMP, 'no-such-repo-xyz')
  check('前置：目标仓库确实不存在', !existsSync(missing), missing)

  let r = null
  let threw = null
  try { r = await b.build({ repoRoot: missing }) } catch (e) { threw = e }

  check('build() 不抛异常（早返回）', threw === null, threw ? String(threw.message) : '')
  check('返回 ok:false 且带 error', r && r.ok === false && typeof r.error === 'string' && r.error.length > 0, JSON.stringify(r))
  check('BV-03 返回形状完整：errors 是数组（旧实现没有这个字段）', r && Array.isArray(r.errors), JSON.stringify(r && Object.keys(r)))
  check('BV-03 计数为 0 而不是 undefined', r && r.errorCount === 0 && r.warningCount === 0, JSON.stringify({ ec: r && r.errorCount, wc: r && r.warningCount }))

  // UD-02（Codex 第四轮指出第一版不完整）：**早返回也必须带 runId 并落 per-run 记录**。
  // 否则调用方拿这次失败去 verify_report(kind=build) 既没 runId 也没记录 → 只能得到含糊的 unverified；
  // 而事实是"这次构建压根没跑"，那是个**确定**的结论（应当判 fail）。
  check('UD-02 早返回也带 runId（第一版遗漏）', typeof r.runId === 'string' && r.runId.length > 0, JSON.stringify(r.runId))
  check('UD-02 未传 runId 时标记为自动生成', r.runIdAutoGenerated === true, JSON.stringify(r.runIdAutoGenerated))
  const perRun = join(logsDir, 'run-' + r.runId + '.json')
  check('UD-02 早返回也落 per-run 记录（证据链不留空洞）', existsSync(perRun), perRun)
  let recOk = null
  try { recOk = JSON.parse(readFileSync(perRun, 'utf8')).ok } catch { /* ignore */ }
  check('UD-02 per-run 记录如实记 ok=false（verify_report 据此判 fail 而非 unverified）', recOk === false, JSON.stringify(recOk))

  // BV-05：早返回必须也写 last.json —— 否则 build_status 报的还是**上一次成功**，
  // 等于把 agent 自己刚触发的失败藏起来（又是一次"陈旧当当前"）。
  const lastP = join(logsDir, 'last.json')
  check('BV-05 早返回也写 last.json（旧实现只在成功路径写）', existsSync(lastP), lastP)
  let lastOk = null
  let lastDidNotRun = null
  try { const j = JSON.parse(readFileSync(lastP, 'utf8')); lastOk = j.ok; lastDidNotRun = j.didNotRun } catch { /* ignore */ }
  check('BV-05 last.json 记的是**失败**（不是上一次的成功）', lastOk === false, JSON.stringify(lastOk))
  check('BV-05 last.json 带 didNotRun 标记（渲染层据此说"没有执行"而不是"编译失败"）', lastDidNotRun === true, JSON.stringify(lastDidNotRun))

  // 关键：渲染不能抛；抛一次就等于把错误换成宿主那行无用的 INVALID_TOOL_OUTPUT
  let text = ''
  let renderThrew = null
  try { text = renderBuild(r) } catch (e) { renderThrew = e }
  check('BV-03 渲染**不抛异常**（旧实现必抛 TypeError）', renderThrew === null, renderThrew ? String(renderThrew.message) : '')
  check('BV-03 渲染保留原始错误文本', /仓库根目录不存在/.test(text), text.slice(0, 200))
  check('BV-03 渲染给出可操作下一步（repoRoot / DSH_BUILD_REPO_ROOT）', /repoRoot/.test(text) && /DSH_BUILD_REPO_ROOT/.test(text), text.slice(0, 300))
}

// ------------------------------------------------- 2. 渲染层抗退化：任何形状都不许抛
{
  const shapes = [
    ['裸失败（无 errors）', { ok: false, error: '仓库根目录不存在：x（传 repoRoot 或设置 DSH_BUILD_REPO_ROOT / DSH_BUILD_CLIENT_ROOT）' }],
    ['空对象失败', { ok: false }],
    ['连 ok 都没有', {}],
    ['null', null],
    ['undefined', undefined],
    ['errors 是 null', { ok: false, error: 'x', errors: null }],
    ['errors 是字符串', { ok: false, error: 'x', errors: 'boom' }],
    ['MSBuild 缺失', { ok: false, error: '未找到 MSBuild（可用 DSH_BUILD_MSBUILD 指定）' }],
    ['dotnet 引擎缺 SDK', { ok: false, error: 'dotnet 引擎需要 PATH 上有 dotnet SDK（或设置 DOTNET_ROOT）' }],
    ['客户端占用', { ok: false, error: '被锁', clientRunning: true, clientPid: 123 }],
    ['超时', { ok: false, timedOut: true, target: 'Build', durationMs: 30000 }],
  ]
  for (const [label, v] of shapes) {
    let threw = null
    let out = ''
    try { out = renderBuild(v) } catch (e) { threw = e }
    check('渲染不抛：' + label, threw === null && typeof out === 'string' && out.length > 0,
      (threw ? String(threw.message) : '') + ' | ' + String(out).slice(0, 80))
  }
  const ms = renderBuild({ ok: false, error: '未找到 MSBuild（可用 DSH_BUILD_MSBUILD 指定）' })
  check('MSBuild 缺失给出 DSH_BUILD_MSBUILD 提示', /DSH_BUILD_MSBUILD/.test(ms), ms.slice(0, 200))
  const cl = renderBuild({ ok: false, error: '被锁', clientRunning: true, clientPid: 123 })
  check('客户端占用给出 killClient 提示', /killClient/.test(cl), cl.slice(0, 200))
}

// ------------------------------------------------- 3. 正常路径：成功与真实编译失败
{
  const ok = renderBuild({ ok: true, target: 'Rebuild', durationMs: 12345, errorCount: 0, warningCount: 3, logPath: 'L.log', errors: [], warnings: [], envErrors: [], envErrorCount: 0 })
  check('成功后渲染 PASSED 与计数', /Rebuild PASSED/.test(ok) && /0 错误 \/ 3 警告/.test(ok), ok.slice(0, 200))

  const failed = renderBuild({
    ok: false, target: 'Build', durationMs: 5000, errorCount: 1, warningCount: 0, logPath: 'L.log',
    errors: [{ file: 'A.cs', line: 12, col: 3, code: 'CS1002', message: "需要 ;" }], warnings: [], envErrors: [], envErrorCount: 0,
  })
  check('编译失败列出关键错误（file:line,col code）', /A\.cs\(12,3\): CS1002/.test(failed), failed.slice(0, 300))
  check('编译失败标题是 FAILED', /FAILED/.test(failed) && !/PASSED/.test(failed), failed.slice(0, 120))

  // 失败 + **有** error 但没有错误条目 → 必须打印 error（旧实现把原因丢了），并说明"这不是编译通过"
  const failedNoErr = renderBuild({ ok: false, target: 'Build', durationMs: 100, errorCount: 0, warningCount: 0, logPath: 'L.log', error: '仓库根目录不存在：X（传 repoRoot 或设置 DSH_BUILD_REPO_ROOT）', errors: [], warnings: [], envErrors: [], envErrorCount: 0 })
  check('失败且无错误条目 → 打印 v.error（不再吞掉原因）', /仓库根目录不存在/.test(failedNoErr), failedNoErr.slice(0, 260))
  check('失败且无错误条目 → 仍给可操作下一步', /DSH_BUILD_REPO_ROOT/.test(failedNoErr), failedNoErr.slice(0, 320))
  check('失败且无错误条目 → 明确"不要当成编译通过"', /不要把它当成/.test(failedNoErr), failedNoErr.slice(0, 360))

  // 失败 + 既无 error 也无错误条目 → 指向 build_errors 与日志路径
  const failedEmpty = renderBuild({ ok: false, target: 'Build', durationMs: 100, errorCount: 0, warningCount: 0, logPath: 'L.log', errors: [], warnings: [], envErrors: [], envErrorCount: 0 })
  check('失败且啥都没有 → 指向 build_errors 与日志路径', /build_errors/.test(failedEmpty) && /L\.log/.test(failedEmpty), failedEmpty.slice(0, 300))

  const env = renderBuild({ ok: false, target: 'Build', durationMs: 100, errorCount: 0, warningCount: 0, logPath: 'L.log', errors: [], warnings: [], envErrorCount: 1, envErrors: [{ code: 'MSB3027', message: '文件被占用' }] })
  check('只读动作区分环境错误（文件锁）', /环境错误/.test(env) && /MSB3027/.test(env), env.slice(0, 260))

  const truncated = renderBuild({ ok: false, target: 'Build', durationMs: 100, errorCount: 50, warningCount: 0, logPath: 'L.log', truncated: true, errors: [{ file: 'A.cs', line: 1, col: 1, code: 'X', message: 'm' }], warnings: [], envErrors: [], envErrorCount: 0 })
  check('截断时提示用 build_errors 看全部', /build_errors/.test(truncated), truncated.slice(0, 320))

  // UD-02：runId 必须印出来（agent 才能把它传给 verify_report），且自动生成时要说明
  const autoRid = renderBuild({ ok: true, target: 'Build', durationMs: 100, errorCount: 0, warningCount: 0, logPath: 'L.log', errors: [], warnings: [], envErrors: [], envErrorCount: 0, runId: 'auto-20260911T1930', runIdAutoGenerated: true })
  check('UD-02 成功后打印 runId', /runId=auto-20260911T1930/.test(autoRid), autoRid.slice(0, 260))
  check('UD-02 自动生成时说明"要验编译通过就把它传给 verify_report"', /verify_report/.test(autoRid) && /自动生成/.test(autoRid), autoRid.slice(0, 320))
  const userRid = renderBuild({ ok: true, target: 'Build', durationMs: 100, errorCount: 0, warningCount: 0, logPath: 'L.log', errors: [], warnings: [], envErrors: [], envErrorCount: 0, runId: 'task-1', runIdAutoGenerated: false })
  check('UD-02 用户传入的 runId 不带"自动生成"字样', /runId=task-1/.test(userRid) && !/自动生成/.test(userRid), userRid.slice(0, 260))
  // per-run 记录写失败必须出声（那是"证据缺失"的另一种来源）
  const evFail = renderBuild({ ok: true, target: 'Build', durationMs: 100, errorCount: 0, warningCount: 0, logPath: 'L.log', errors: [], warnings: [], envErrors: [], envErrorCount: 0, runId: 'r', evidenceWriteError: 'per-run 构建记录写入失败：磁盘满' })
  check('UD-02 per-run 记录写失败必须显式警告', /⚠/.test(evFail) && /写入失败/.test(evFail), evFail.slice(0, 320))
}

rmSync(TMP, { recursive: true, force: true })
console.log(failures ? `\nFAILED: ${failures} 项` : '\nPASS: dsh-build render（BV-03 早返回不再吃掉错误）')
process.exit(failures ? 1 : 0)
