/**
 * dsh-build 渲染层 — `build_run` 的 agent 可见文本。
 *
 * 为什么单独成模块（与 dsh-perf / dsh-ui-drive / dsh-hang-inspector 同一先例）：
 * 渲染文本是契约的一部分，而 index.js 依赖宿主的 `@deepseek-ai/dsh-tools`
 * （普通 node 进程 import 不到），留在里面就等于不可测。
 *
 * BV-03（2026-09-11 审计确证）：旧实现在 `if (!v.ok && v.errors.length > 0)` 处**无条件**
 * 读 `v.errors.length`，而 `build()` 的 6 条早返回（含最常见的"没传 repoRoot"）没有 `errors` 字段
 * → TypeError → 宿主把它换成 `INVALID_TOOL_OUTPUT: output.render failed`。
 * 后果不是"少了一行信息"，而是**唯一能自救的那句话被整个吃掉**。
 *
 * 所以这里的第一原则：**渲染层永远不能抛**。形状不全就少说，不能因此把错误信息换成无用的宿主错误。
 */

/** 按错误文本给下一步 —— 这是"错误可操作"的全部价值所在。 */
function hintsFor(err) {
  const s = String(err || '')
  // BV-04（2026-09-11，Codex 复核确认）：配置缺失必须**先判并排除**。
  // 否则 `/客户端/` 会先命中下面那条通用提示，给出的建议是"传 killClient=true 结束客户端再构建" ——
  // 而在"进程名都没配"的场景里这条建议**根本做不到**（killClient 无法定位目标），
  // 只会把 agent 往死路上再带一圈。这正是 BV-04 要修的"把没配置诊断成客户端未运行"的渲染版。
  if (/DSH_BUILD_CLIENT_PROC|DSH_UI_PROC_NAME|进程名未配置/.test(s)) {
    return '\n（下一步：设置 DSH_BUILD_CLIENT_PROC=<客户端进程名>（或 DSH_UI_PROC_NAME），killClient=true 才可能生效；' +
      '也可以先手工关闭目标客户端再构建）'
  }
  return (/仓库根|repoRoot|DSH_BUILD_REPO_ROOT/i.test(s)
    ? '\n（下一步：显式传 repoRoot=<仓库根绝对路径>，或设置环境变量 DSH_BUILD_REPO_ROOT / DSH_BUILD_CLIENT_ROOT）' : '') +
    (/MSBuild/i.test(s) ? '\n（下一步：设置 DSH_BUILD_MSBUILD 指向 MSBuild.exe）' : '') +
    (/dotnet/i.test(s) ? '\n（下一步：确认 PATH 上有 dotnet SDK，或改用 engine=msbuild）' : '') +
    (/客户端|clientRunning|被锁/i.test(s) ? '\n（下一步：确认后传 killClient=true 结束客户端再构建，或先手工关闭它）' : '') +
    // BV-04：killClient 明确没能生效时，别把 agent 留在"再传一次 killClient"的循环里。
    (/无法生效|clientKillSkipped/i.test(s) ? '\n（本轮已传 killClient=true 仍未生效 —— 原因在上面，重复传参不会改变结果）' : '')
}

/** 人类可读的年龄（用于"最近一次构建"的陈旧警告）。 */
function ageText(ms) {
  if (!Number.isFinite(ms)) return '?'
  const min = ms / 60000
  if (min < 1) return '刚刚'
  if (min < 60) return Math.round(min) + ' 分钟前'
  const h = min / 60
  if (h < 24) return (Math.round(h * 10) / 10) + ' 小时前'
  return (Math.round(h / 24 * 10) / 10) + ' 天前'
}

/**
 * build_status（"最近一次构建结果"）的渲染。
 *
 * 四个实测踩出来的问题（CL-7 / CL-3 / BV-05）：
 *  1. **没有年龄**：只说"最近构建"不说"多久以前" → 昨天的成功被当成当前状态（同 F-005 的病）。
 *  2. `v.durationMs / 1000` 在 `durationMs` 为 null 时算出 **NaN**，打出"耗时 NaN s"。
 *     早返回路径的 `durationMs` 就是 null（根本没跑）。
 *  3. 早返回时 `v.target` 可能为 null → 打出"最近构建：null 失败(0 错误)"，
 *     看着像工具坏了，而真相是"这次构建压根没启动"。
 *  4. **计数自相矛盾**：`warningCount` 是本工具解析去重后的条数，`summaryLine` 是 MSBuild 自己
 *     汇总行里的数字，两者口径不同（实测 15 vs 32）。直接并排显示会让人以为其中一个是错的。
 *     现在两者都保留，但**明说它们是不同口径**，而不是让调用方去猜。
 */
export function renderStatus(v, now = Date.now()) {
  if (!v || v.hasRun !== true) return '还没有构建记录（先 build_run；或设置了 DSH_BUILD_LOGS_DIR 指向别处）'
  const when = v.at ? new Date(v.at) : null
  const ageMs = when && Number.isFinite(when.getTime()) ? now - when.getTime() : null
  const ageTag = ageMs !== null ? '（' + ageText(ageMs) + '）' : ''

  // 早返回（根本没跑）：说清是"没启动"，不要摆出一串 null/NaN。
  // 判定用**显式标记**而不是猜特征：failResult 会把 errorCount 补成 0（有限值），
  // 靠"errorCount 不是数字"来判会永远不触发（我第一版就是这么错的）。
  if (v.ok === false && (v.didNotRun === true || (v.durationMs === null && v.logPath === null))) {
    return '最近一次构建**没有执行**' + ageTag + '：' + (v.error || '原因未回报') +
      (v.runId ? '\nrunId=' + v.runId : '') +
      '\n（这不等于"编译失败" —— 是压根没开始。修掉上面的原因后重跑 build_run。）'
  }

  const dur = Number.isFinite(v.durationMs) ? (v.durationMs / 1000).toFixed(1) + 's' : '?'
  const ec = Number.isFinite(v.errorCount) ? v.errorCount : null
  const wc = Number.isFinite(v.warningCount) ? v.warningCount : null
  const head = '最近构建：' + (v.target || '(未指定)') + ' ' + (v.ok ? '通过' : '失败') +
    (ec !== null ? '(' + ec + ' 错误)' : '') + '，耗时 ' + dur + '，日志 ' + (v.logPath || '?') + ageTag

  const notes = []
  if (ageMs !== null && ageMs >= 30 * 60 * 1000) {
    notes.push('⚠ 这是 ' + ageText(ageMs) + ' 的构建记录 —— 它不能证明**此刻**的代码能编译；' +
      '要拿这个结论请重新 build_run。')
  }
  if (v.runId) notes.push('runId=' + v.runId + (v.runIdAutoGenerated ? '（自动生成）' : '') + ' —— 传给 verify_report(kind=build) 即可让 claim 有据可依。')
  // CL-7：两种口径并存时明说，不让调用方以为其中一个是错的
  if (v.summaryLine && wc !== null) {
    const m = String(v.summaryLine).match(/(\d+)\s*error\(s\),\s*(\d+)\s*warning\(s\)/i)
    if (m && Number(m[2]) !== wc) {
      notes.push('ℹ 计数口径不同：本工具解析去重后 ' + wc + ' 条警告，MSBuild 汇总行自报 ' + m[2] + ' 条（"'
        + String(v.summaryLine).slice(0, 60) + '"）。两者都不是错的 —— 前者是去重后的实际条目数，' +
        '后者是编译器自己的累计计数。要用哪个取决于你的目的，别把它们当同一个数比较。')
    }
  }
  if (v.evidenceWriteError) notes.push('⚠ ' + v.evidenceWriteError)
  // F-007：陈旧代码必须自曝 —— 否则"修复没生效"会被误读成"功能不存在"
  if (v.codeStaleNote) notes.push(v.codeStaleNote)
  return [head, ...notes].join('\n')
}

/**
 * build_run 的渲染。
 *
 * BV-04（2026-09-11）：外层只做一件事 —— **把客户端状态的三态尾巴挂在每一条返回路径上**。
 * 旧实现里 `clientRunningWarning` 是 builder 算好的字段，而渲染层一个字都没印（又一处"算出来了没印出来"）。
 * 与其在 5 条 return 上各挂一次（那正是"同一漏洞修一半"的温床），不如包一层。
 */
export function renderBuild(v) {
  const core = renderBuildCore(v)
  const notes = []
  if (v && v.clientUnconfigured) {
    notes.push('⚠ 客户端进程名未配置（DSH_BUILD_CLIENT_PROC / DSH_UI_PROC_NAME 都没设）：' +
      '本次是「**无法判断**客户端是否在运行」，不是「客户端没在跑」。要能自动结束客户端（killClient=true）请先配上进程名。')
  }
  if (v && v.clientUnconfiguredNote) notes.push('ℹ ' + v.clientUnconfiguredNote)
  if (v && v.clientRunningWarning) notes.push('ℹ ' + v.clientRunningWarning)
  if (v && v.codeStaleNote) notes.push(v.codeStaleNote)
  // **成功 ≠ 新文件进了编译**（Codex r17 #5，用户最可能踩的坑）：
  //   legacy .csproj 里**新增的 .cs 必须手工加 <Compile Include>**，否则文件压根不参与编译，
  //   而构建照样报"错误数 0"。此前这条坑只写在插件 GUIDANCE（系统提示）里，**结果里一个字都没有** ——
  //   于是拿到"构建成功"的 agent 完全可能漏判。
  //   只在**定向 .csproj** 的构建上加这一句（整解决方案构建不加，避免每次刷屏）。
  if (v && v.ok === true && /\.csproj$/i.test(String(v.project || ''))) {
    notes.push('⚠ 成功只证明「编译器没报错」：legacy .csproj 里**新增的 .cs 必须手工加 <Compile Include>**，' +
      '否则该文件**根本没参与编译**（错误数 0 也可能是这种情况）。\n' +
      '  核对法：`git status` 里新增/改名的 .cs，是否都能在 ' + String(v.project) + ' 的 <Compile Include="…"/> 列表里找到；找不到就是没进编译。')
  }
  // runId 过去只印在**成功**路径上；失败路径一条都不印（实测：BV-04 的失败结果里只有 error）。
  // 但失败同样写了 per-run 记录（earlyFail 也写 run-<id>.json），不印 runId 就等于
  // 「凭证存在但 agent 不知道去哪找」。放在这一层，5 条 return 一条都漏不掉。
  if (v && v.runId && !String(core).includes(String(v.runId))) {
    notes.push('runId=' + v.runId + (v.runIdAutoGenerated ? '（自动生成）' : '') +
      ' —— 本次的 per-run 记录已落盘（失败也写），可用它串 verify_report / build_status。')
  }
  return notes.length ? core + '\n' + notes.join('\n') : core
}

function renderBuildCore(v) {
  if (!v) return '构建没有返回结果（工具执行异常）'
  if (v.clientRunning && !v.killClient) {
    return '客户端正在运行（PID ' + v.clientPid + '），输出文件被锁无法构建：' + v.error + hintsFor(v.error)
  }
  if (!v.ok && v.timedOut) return '构建超时（' + ((v.durationMs || 0) / 1000).toFixed(0) + 's）：' + v.target
  if (v.spawnError) return '构建无法启动：' + v.spawnError

  const errors = Array.isArray(v.errors) ? v.errors : []
  const envErrors = Array.isArray(v.envErrors) ? v.envErrors : []
  const errorCount = Number.isFinite(v.errorCount) ? v.errorCount : errors.length
  const warningCount = Number.isFinite(v.warningCount) ? v.warningCount : 0
  const head = (v.target === 'Rebuild' ? 'Solution Rebuild' : 'Incremental/targeted build') + ' ' +
    (v.ok ? 'PASSED' : 'FAILED') +
    '（' + ((v.durationMs || 0) / 1000).toFixed(1) + 's，' + errorCount + ' 错误 / ' + warningCount + ' 警告，日志 ' + (v.logPath || '?') + '）'

  if (!v.ok && errors.length > 0) {
    return head + '\n关键错误：\n' +
      errors.slice(0, 10).map((e) => e.file + '(' + e.line + ',' + e.col + '): ' + e.code + ': ' + e.message).join('\n') +
      (v.truncated ? '\n…(错误已截断，用 build_errors 看全部)' : '')
  }
  if (!v.ok && envErrors.length > 0) {
    return head + '\n环境错误（文件锁，非代码错误）：' +
      envErrors.slice(0, 4).map((e) => e.code + ': ' + String(e.message).slice(0, 120)).join('\n')
  }
  // 失败、且日志里没有可列的错误条目 —— 这时**唯一的信息就是 v.error**。
  // BV-03 的教训：这条分支过去直接收尾，把 error 丢掉了（修了形状却仍然吞掉原因）。
  if (!v.ok) {
    if (v.error) {
      return head + '\n原因：' + v.error + hintsFor(v.error) +
        '\n（这条失败发生在**读取/解析日志之前**，所以没有错误条目可列 —— 不要把它当成"编译通过"。）'
    }
    return head + '\n（失败，但既没有 error 也没有解析出错误条目 —— 用 build_errors 看原始日志，' +
      '或确认日志路径 ' + (v.logPath || '?') + ' 是否可读）'
  }
  // UD-02（Claude 第三轮）：把 runId 印出来，agent 才能把它原样传给 verify_report(kind=build)。
  // 过去 runId 是可选且不自动生成的，漏传就**结构性**地让 build claim 永远 unverified。
  const rid = v.runId
    ? '\nrunId=' + v.runId + (v.runIdAutoGenerated ? '（本次自动生成 —— 要验"编译通过"就把这个 runId 传给 verify_report）' : '（把它传给 verify_report 即可让 build claim 有据可依）')
    : ''
  if (v.evidenceWriteError) {
    return head + rid + '\n⚠ ' + v.evidenceWriteError
  }
  return head + rid
}
